services:
  - type: web
    name: nomaya
    runtime: python
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nomaya.settings
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      # SECRET_KEY, ALLOWED_HOSTS vb. ortam değişkenlerini Render panelinden ekleyebilirsin
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn nomaya.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --graceful-timeout 30
    healthCheckPath: /healthz/
