# Generated by Django 4.2.23 on 2025-10-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('location_text', models.CharField(blank=True, max_length=160)),
                ('points', models.JSONField(blank=True, help_text='List[str] – madde listesi', null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='activities/photos/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, unique=True)),
                ('icon', models.CharField(choices=[('check', 'Check'), ('arrow', 'Arrow'), ('info', 'Info')], default='check', max_length=12)),
                ('tags', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AlterModelOptions(
            name='airporttransfer',
            options={'ordering': ['city__name', 'direction']},
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='day',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='from_airport',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='to_hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='day',
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='airport_transfers', to='core.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='direction',
            field=models.CharField(choices=[('A2H', 'Airport → Hotel'), ('H2A', 'Hotel → Airport')], default='A2H', max_length=3),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_transfers', to='core.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='day',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tour',
            name='compare_at_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='airporttransfer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='day',
            name='bullets',
            field=models.JSONField(blank=True, help_text='List[str] – 5..10 madde (opsiyonel)', null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_number',
            field=models.PositiveIntegerField(help_text='Şehir içindeki sıra (1..N)'),
        ),
        migrations.AlterField(
            model_name='day',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='DayTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.day')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.airporttransfer')),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'transfer')},
            },
        ),
        migrations.CreateModel(
            name='DayHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.day')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hotel')),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='DayFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.day')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flight')),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'flight')},
            },
        ),
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.day')),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'activity')},
            },
        ),
        migrations.AddField(
            model_name='day',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='days', through='core.DayActivity', to='core.activity'),
        ),
        migrations.AddField(
            model_name='day',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='days', through='core.DayFlight', to='core.flight'),
        ),
        migrations.AddField(
            model_name='day',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='days', through='core.DayHotel', to='core.hotel'),
        ),
        migrations.AddField(
            model_name='day',
            name='transfers',
            field=models.ManyToManyField(blank=True, related_name='days', through='core.DayTransfer', to='core.airporttransfer'),
        ),
        migrations.CreateModel(
            name='TourBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('highlights', 'Tour Highlights'), ('more_about', 'More About')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='core.bullet')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bullets', to='core.tour')),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
                'indexes': [models.Index(fields=['tour', 'section'], name='core_tourbu_tour_id_9fb437_idx')],
                'unique_together': {('tour', 'bullet', 'section')},
            },
        ),
    ]
