# Generated by Django 4.2.23 on 2025-10-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_bullet_alter_airporttransfer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Tur içindeki gün sırası (1..N)')),
                ('date', models.DateField(blank=True, help_text='Opsiyonel: bu günün takvim tarihi', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_tours', to='core.day')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='core.tour')),
            ],
            options={
                'ordering': ['tour', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='tours_for', through='core.TourDay', to='core.day'),
        ),
        migrations.AddIndex(
            model_name='tourday',
            index=models.Index(fields=['tour', 'order'], name='core_tourda_tour_id_eeb99f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourday',
            unique_together={('tour', 'order'), ('tour', 'day')},
        ),
    ]
