# Generated by Django 4.2.23 on 2025-10-07 12:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tourday_tour_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Toplam gün fiyatı ile çarpılacak katsayı (1.00–2.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('2.00'))]),
        ),
    ]
