# Generated by Django 4.2.23 on 2025-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tour_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
