# Generated by Django 4.2.23 on 2025-10-07 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity_price_activity_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel')], default='hotel', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('same_room', models.BooleanField(default=True)),
                ('hide_flights', models.BooleanField(default=False)),
                ('hide_transfers', models.BooleanField(default=False)),
                ('hide_hotels', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tour')),
            ],
        ),
    ]
