# Generated by Django 4.2.23 on 2025-10-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hotel_address_hotel_hotel_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourday',
            unique_together=set(),
        ),
    ]
