# Generated by Django 4.2.23 on 2025-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tourday_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, help_text='Customer contact e-mail for this order', max_length=254, null=True),
        ),
    ]
