# Generated by Django 4.2.23 on 2025-10-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1, help_text='Traveler sequence number for this order')),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='core.order')),
            ],
            options={
                'ordering': ['order_id', 'index', 'id'],
            },
        ),
    ]
