# Generated by Django 4.2.23 on 2025-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_traveler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveler',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='index',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='traveler',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='passport_no',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
