# Generated by Django 4.2.23 on 2025-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_traveler_options_remove_traveler_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_types',
            field=models.ManyToManyField(blank=True, related_name='tours', to='core.tourtype'),
        ),
    ]
