# Generated by Django 4.2.23 on 2025-10-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
