# Generated by Django 4.2.23 on 2025-10-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourday',
            options={'ordering': ('order', 'id')},
        ),
        migrations.RemoveIndex(
            model_name='tourday',
            name='core_tourda_tour_id_eeb99f_idx',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='note',
        ),
        migrations.AddField(
            model_name='tourday',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Day Title'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.day'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
